import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

function mcq(q:string,opts:string[],c:number,ex:string){return{type:'multiple_choice',question:q,options:opts,correct:c,explanation:ex}}
function tf(q:string,ans:boolean,ex:string){return{type:'true_false',question:q,answer:ans,explanation:ex}}
function fb(q:string,ans:string,ex:string){return{type:'fill_blank',question:q,answer:ans,explanation:ex}}

async function main(){
console.log('🚀 Seeding VibeCode Academy...\n');

// Clear
await prisma.userBadge.deleteMany();
await prisma.userLessonProgress.deleteMany();
await prisma.userProject.deleteMany();
await prisma.lesson.deleteMany();
await prisma.project.deleteMany();
await prisma.module.deleteMany();
await prisma.badge.deleteMany();
await prisma.glossaryTerm.deleteMany();
await prisma.dailyChallenge.deleteMany();
await prisma.user.deleteMany();

// ==================== MODULES ====================
const modules = await Promise.all([
  prisma.module.create({data:{name:'Welcome to the AI Coding Era',slug:'welcome',description:'Discover vibe coding and build your first app in minutes!',icon:'🚀',color:'#58CC02',order:1}}),
  prisma.module.create({data:{name:'The Language of Tech',slug:'language-of-tech',description:'Learn the vocabulary every vibe coder needs — no jargon, just clarity.',icon:'📖',color:'#1CB0F6',order:2}}),
  prisma.module.create({data:{name:'Prompt Engineering Mastery',slug:'prompt-engineering',description:'The #1 skill for vibe coding. Write prompts that get results.',icon:'✨',color:'#FF9600',order:3}}),
  prisma.module.create({data:{name:'Your AI Toolbox',slug:'ai-toolbox',description:'Master the tools: Lovable, Bolt, v0, Replit, Cursor & Claude.',icon:'🧰',color:'#A560E8',order:4}}),
  prisma.module.create({data:{name:'Building Your First Real App',slug:'first-app',description:'Go from idea to deployed app, step by step.',icon:'🏗️',color:'#FF4B4B',order:5}}),
  prisma.module.create({data:{name:'Version Control & Git',slug:'git',description:'Save your work, undo mistakes, and collaborate like a pro.',icon:'🔀',color:'#00BCD4',order:6}}),
  prisma.module.create({data:{name:'Security & Safety',slug:'security',description:'Protect your apps, your users, and yourself.',icon:'🛡️',color:'#F44336',order:7}}),
  prisma.module.create({data:{name:'Deployment & DevOps',slug:'deployment',description:'Put your app on the internet for the world to see.',icon:'☁️',color:'#4CAF50',order:8}}),
  prisma.module.create({data:{name:'Working with APIs & Data',slug:'apis-data',description:'Connect your app to the world — payments, maps, AI, and more.',icon:'🔌',color:'#FF5722',order:9}}),
  prisma.module.create({data:{name:'Design & UX',slug:'design-ux',description:'Make your apps beautiful and easy to use.',icon:'🎨',color:'#E91E63',order:10}}),
  prisma.module.create({data:{name:'Advanced Vibe Coding',slug:'advanced',description:'Real-time features, payments, AI integration, and more.',icon:'⚡',color:'#795548',order:11}}),
  prisma.module.create({data:{name:'Ship It! Launch & Grow',slug:'ship-it',description:'Launch your app and grow your audience.',icon:'🚢',color:'#FFD700',order:12}}),
]);

// ==================== MODULE 1: WELCOME (10 lessons) ====================
console.log('🚀 Module 1: Welcome');
const m1 = modules[0];
const m1Lessons = [
  {title:'What is Vibe Coding?',slug:'what-is-vibe-coding',order:1,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Imagine you could describe an app to a super-smart assistant, and they'd build it for you in minutes. That's vibe coding! Coined by AI legend Andrej Karpathy, it means building software by having a conversation with AI — no coding syntax to memorize, no years of training needed.",keyPoints:["AI writes code from your descriptions","No programming languages to learn","Focus on WHAT you want, not HOW to code it","Millions of people are already doing this"],realWorldExample:"Karpathy himself built a complete web app by talking to an AI assistant, barely looking at the code.",eli10:"It's like telling a robot exactly what LEGO creation you want, and the robot builds it for you. You just say 'I want a castle with a drawbridge' and boom — castle!"}),
    demo:JSON.stringify({tool:"lovable",steps:[{instruction:"Go to lovable.dev and sign up for a free account",screenshot:"signup"},{instruction:"Type: 'Build me a personal portfolio website with a hero section that says Hello World, an about me section, and a contact form'",screenshot:"prompt"},{instruction:"Watch Lovable generate your entire website in under 60 seconds!",screenshot:"result"}]}),
    quiz:JSON.stringify([mcq("Who coined the term 'vibe coding'?",["Elon Musk","Andrej Karpathy","Sam Altman","Mark Zuckerberg"],1,"Andrej Karpathy, a renowned AI researcher, coined 'vibe coding' in early 2025."),tf("You need to learn JavaScript before you can vibe code.",false,"That's the whole point — vibe coding lets you build without knowing programming languages!"),mcq("What do you focus on in vibe coding?",["Writing perfect syntax","Memorizing functions","Describing WHAT you want","Reading documentation"],2,"Vibe coding shifts focus from HOW (syntax) to WHAT (requirements). You describe the outcome, AI handles the code.")]),
    challenge:JSON.stringify({type:"project_task",description:"Open Lovable and create a simple landing page for an imaginary product. It should have a headline, description, and a button.",criteria:["Has a clear headline","Has a product description","Has a call-to-action button"],xpBonus:50})},

  {title:'How AI Changed Software Development',slug:'how-ai-changed-dev',order:2,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Before 2023, building an app meant years of learning. First HTML, then CSS, then JavaScript, then a framework, then databases... it took 6-12 months just to build a simple to-do app. Now? You can describe that app in one sentence and have it running in 5 minutes. AI didn't just speed things up — it completely changed who can build software.",keyPoints:["Traditional coding: years of learning → simple apps","AI coding: minutes of prompting → working apps","The barrier to entry dropped from years to hours","Anyone with an idea can now build it"],realWorldExample:"A marketing manager with zero coding experience built a customer dashboard for her team in one afternoon using Bolt.new.",eli10:"Before: Only trained chefs could cook in restaurants. Now: You tell a robot chef what you want to eat, and it cooks it perfectly. Anyone can 'cook' now!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("How long did it typically take to learn to build a basic app the traditional way?",["A few hours","6-12 months","10 years","1 week"],1,"Traditional coding requires learning multiple languages, frameworks, and tools — a process that takes months."),mcq("What's the biggest change AI brought to software development?",["Faster computers","Better monitors","Non-programmers can now build apps","Cheaper hosting"],2,"The revolutionary change is democratization — people who never coded can now build real software.")]),
    challenge:undefined},

  {title:'What You Can Build Without Coding Experience',slug:'what-you-can-build',order:3,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Think vibe coding is only for simple websites? Think again. People with zero coding background are building: SaaS products that make money, internal tools for their companies, mobile apps, AI-powered chatbots, e-commerce stores, and even games. The limit isn't your coding skill anymore — it's your imagination and how well you can describe what you want.",keyPoints:["Landing pages & portfolio sites (5 min)","Full web apps with databases (1-2 hours)","AI-powered chatbots & tools (30 min)","E-commerce stores with payments","Internal company dashboards","Mobile-responsive web apps"],realWorldExample:"A teacher built an AI-powered quiz generator for her students in one evening, saving hours of manual work each week.",eli10:"You know how some toys only let you build what's on the box? Vibe coding is like having infinite LEGO pieces — you can build literally anything you can imagine!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("Which of these can you build with vibe coding?",["Only static websites","Only simple forms","Full apps with databases, auth, and payments","Only prototypes"],2,"Vibe coding tools can build complete, production-ready applications with all features."),tf("You need a team of developers to build a SaaS product.",false,"Solo non-coders have built profitable SaaS products using AI coding tools.")]),
    challenge:undefined},

  {title:'Gallery: Real Apps Built by Non-Coders',slug:'gallery-real-apps',order:4,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Let's look at real examples of what non-technical people have built. These aren't toy projects — they're real apps with real users making real money. A fitness coach built a client tracking app. A real estate agent built a property listing site with search filters. A student built a study group coordinator. A restaurant owner built an online ordering system. All without writing a single line of code themselves.",keyPoints:["Fitness tracking app — built by a gym owner","Property listings — built by a real estate agent","Study coordinator — built by a college student","Restaurant ordering — built by a restaurant owner","Each was built in 1-3 days, not months"],realWorldExample:"These are composites of real stories from the vibe coding community. The tools they used: Lovable, Bolt, and Replit.",eli10:"Imagine if kids who never learned to draw could suddenly make amazing art just by describing what they see in their head. That's what happened with coding!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What's a common trait of successful vibe coders?",["They learned to code first","They have CS degrees","They clearly know WHAT they want to build","They only use one tool"],2,"The key skill is knowing your problem and being able to describe the solution clearly."),tf("Apps built with vibe coding are only prototypes, not real products.",false,"Many vibe-coded apps serve real users and generate revenue.")]),
    challenge:undefined},

  {title:'Your First 5 Minutes: Build a Landing Page',slug:'first-five-minutes',order:5,difficulty:'BEGINNER' as const,estimatedMinutes:8,
    concept:JSON.stringify({story:"Enough theory — let's BUILD something! In the next 5 minutes, you'll create a real website that anyone in the world can visit. We'll use Lovable because it's the easiest tool for beginners. You'll type a description of what you want, and Lovable will create the entire website — design, code, and all. Then you'll deploy it with one click.",keyPoints:["Lovable is the easiest tool for absolute beginners","Describe your app in plain English","Lovable generates the full website","One click to deploy and share with the world","Your first creation in under 5 minutes!"],realWorldExample:"Every vibe coder remembers their first build. It's the moment you realize 'I can actually DO this.' Let's create that moment for you.",eli10:"We're going to tell the computer what to draw, and it's going to draw it for us. Like magic art, but it's a real website!"}),
    demo:JSON.stringify({tool:"lovable",steps:[{instruction:"Open lovable.dev and sign in",screenshot:"login"},{instruction:"Click 'New Project' and type this prompt: 'Create a modern landing page for a fictional coffee shop called Brew & Beyond. Include a hero section with a catchy tagline, a menu section with 6 coffee drinks and prices, an about section, and a contact form. Use warm brown and cream colors.'",screenshot:"prompt"},{instruction:"Wait 30-60 seconds while Lovable builds your site",screenshot:"building"},{instruction:"Preview your site! Scroll through it. It's a real website!",screenshot:"preview"},{instruction:"Click 'Deploy' in the top right to make it live. You now have a real URL!",screenshot:"deploy"}]}),
    quiz:JSON.stringify([mcq("What's the first step in Lovable?",["Write HTML code","Draw a wireframe","Describe what you want in plain English","Install Node.js"],2,"Just type what you want! Lovable handles all the technical parts."),tf("You need to know HTML to use Lovable.",false,"Lovable creates all the HTML, CSS, and JavaScript for you. You just describe what you want.")]),
    challenge:JSON.stringify({type:"project_task",description:"Build your own landing page with Lovable! Choose any theme: a coffee shop, a pet store, a personal blog, or anything you like. Deploy it and share the URL!",criteria:["Has a hero section with a headline","Has at least 3 content sections","Has a contact form or call-to-action","Is deployed and accessible via URL"],xpBonus:75})},

  {title:'The Vibe Coder Mindset',slug:'vibe-coder-mindset',order:6,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Vibe coding requires a different mindset than traditional coding. You're not a coder — you're a product manager, a creative director, and a quality tester all in one. Your job is to: 1) Know exactly what you want. 2) Describe it clearly. 3) Test what the AI builds. 4) Iterate until it's right. The best vibe coders aren't the most technical — they're the best communicators.",keyPoints:["Think like a product manager, not a programmer","Your #1 skill is clear communication","Always test what AI generates","Iterate: prompt → test → refine → repeat","Perfection comes from good feedback, not good code"],realWorldExample:"The most successful vibe coders spend 80% of their time on planning and testing, and only 20% on prompting.",eli10:"It's like being the director of a movie. You don't act, you don't do cameras. But you tell everyone exactly what the movie should look like, and you watch the scenes to make sure they're right!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What's the most important skill for a vibe coder?",["Typing speed","Clear communication and testing","Knowing JavaScript","Having a fast computer"],1,"Clear communication = better prompts = better results. Testing ensures quality."),mcq("What percentage of time should you spend on planning and testing vs prompting?",["10% planning, 90% prompting","50/50","80% planning/testing, 20% prompting","100% prompting"],2,"The best vibe coders plan carefully and test thoroughly. The prompting itself is the easy part.")]),
    challenge:undefined},

  {title:'Meet Your AI Tools',slug:'meet-ai-tools',order:7,difficulty:'BEGINNER' as const,estimatedMinutes:6,
    concept:JSON.stringify({story:"There are 6 major AI coding tools, each with different strengths. Think of them like different vehicles — a bicycle is great for short trips, a car for longer ones, and a truck for heavy loads. Lovable is the bicycle (easiest, fastest for simple apps). Bolt is the car (more power, more control). v0 is the design studio (beautiful UIs). Replit is the workshop (build anything). Cursor is the pro garage (for power users). Claude Code is the command center (terminal-based, most powerful).",keyPoints:["Lovable — Easiest, best for beginners, idea → app in minutes","Bolt.new — More control, built-in backend, great for dashboards","v0 by Vercel — Best for UI design and React components","Replit Agent — Build anything, built-in hosting","Cursor — AI-powered code editor for power users","Claude Code — Terminal-based, most capable for complex projects"],realWorldExample:"Most beginners start with Lovable, graduate to Bolt or Replit, and eventually explore Cursor or Claude Code as they grow.",eli10:"Imagine a toy store with different building kits. Some are easy (snap together), some are medium (need some assembly), and some are advanced (build from scratch). You pick the one that matches what you want to build!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("Which tool is best for absolute beginners?",["Cursor","Claude Code","Lovable","v0"],2,"Lovable is designed for non-technical users. It handles everything from code to deployment."),mcq("Which tool is best for UI/design prototyping?",["Replit","Lovable","v0 by Vercel","Cursor"],2,"v0 is laser-focused on generating beautiful React/Next.js UI components."),mcq("Which tool gives you the most control and power?",["Lovable","v0","Bolt","Cursor / Claude Code"],3,"Cursor and Claude Code are for power users who want full control over their codebase.")]),
    challenge:undefined},

  {title:'AI Capabilities vs Limitations',slug:'ai-capabilities-limitations',order:8,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"AI is incredibly powerful, but it's not magic. Knowing what AI CAN'T do is just as important as knowing what it can. AI CAN: generate working code, create beautiful designs, set up databases, deploy apps. AI CAN'T: understand your business perfectly, guarantee security, replace testing, or make creative decisions for you. The biggest mistake beginners make is trusting AI blindly without checking its work.",keyPoints:["CAN: Generate full applications from descriptions","CAN: Create databases, APIs, authentication","CAN: Deploy and host your apps","CAN'T: Guarantee code is secure (40%+ has vulnerabilities)","CAN'T: Know your business requirements without clear prompts","CAN'T: Replace human testing and review","CAN'T: Make good decisions about what to build"],realWorldExample:"A developer trusted AI-generated code for a payment system without review. It had a critical security flaw that could have exposed customer credit card data. Always. Test. Everything.",eli10:"AI is like a super-fast helper who's really smart but sometimes makes mistakes. You need to check their work, just like a teacher checks homework!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What percentage of AI-generated code may contain security flaws?",["Less than 5%","About 10%","Over 40%","0%"],2,"Studies show over 40% of AI-generated code contains security vulnerabilities. Always review!"),tf("AI can perfectly understand your business requirements from a short prompt.",false,"AI needs detailed, clear prompts. It can't read your mind or understand unspoken requirements."),mcq("What's the biggest mistake beginners make?",["Using AI at all","Trusting AI output without testing","Writing long prompts","Using multiple tools"],1,"Blindly trusting AI without verification is the #1 mistake. Always test what AI generates.")]),
    challenge:undefined},

  {title:'Setting Up Your Workspace',slug:'setting-up-workspace',order:9,difficulty:'BEGINNER' as const,estimatedMinutes:8,
    concept:JSON.stringify({story:"Before we dive deeper, let's set up all the accounts you'll need. Think of this as getting your tools ready before a workshop. The good news: everything has a free tier, so you won't spend a penny to get started. We'll set up accounts for Lovable, Replit, GitHub, and Vercel — the four tools you'll use most in this course.",keyPoints:["All tools have free tiers — no cost to start","Lovable account for easy app building","Replit account for coding projects","GitHub account for saving your code","Vercel account for deploying apps","Use a strong, unique password for each!"],realWorldExample:"Professional developers use these same tools. By setting them up now, you're using the same workflow as Silicon Valley engineers.",eli10:"We're getting our art supplies ready! Pencils (Lovable), paint (Replit), a sketchbook (GitHub), and a gallery to show your art (Vercel)."}),
    demo:JSON.stringify({tool:"multiple",steps:[{instruction:"Go to lovable.dev → Sign up with Google or email",screenshot:"lovable"},{instruction:"Go to replit.com → Sign up with Google or email",screenshot:"replit"},{instruction:"Go to github.com → Sign up (choose Free plan)",screenshot:"github"},{instruction:"Go to vercel.com → Sign up with your GitHub account",screenshot:"vercel"}]}),
    quiz:JSON.stringify([tf("You need to pay to use Lovable, Replit, GitHub, or Vercel.",false,"All four have generous free tiers perfect for learning and building."),mcq("Why sign up for Vercel with your GitHub account?",["It's required","It automatically connects your code to deployment — push code, site updates!","It's cheaper","GitHub owns Vercel"],1,"Connecting Vercel to GitHub enables automatic deployments whenever you push code changes.")]),
    challenge:JSON.stringify({type:"project_task",description:"Create accounts on all 4 platforms: Lovable, Replit, GitHub, and Vercel. Take a screenshot of each dashboard as proof!",criteria:["Lovable account created","Replit account created","GitHub account created","Vercel account created"],xpBonus:30})},

  {title:'Your Learning Path',slug:'your-learning-path',order:10,difficulty:'BEGINNER' as const,estimatedMinutes:4,
    concept:JSON.stringify({story:"Congratulations — you've completed Module 1! You now understand what vibe coding is, what tools are available, and you've even built your first website. Here's what's coming next: Module 2 teaches you the language of tech (so you understand what AI is building). Module 3 makes you a prompt engineering pro. Module 4 gives you hands-on experience with every major tool. By Module 5, you'll build your first real app from scratch. Modules 6-12 take you from builder to launcher — security, deployment, design, and shipping products to real users.",keyPoints:["Module 2: Learn tech vocabulary (APIs, databases, hosting)","Module 3: Master prompt engineering","Module 4: Hands-on with every AI tool","Module 5: Build your first complete app","Modules 6-12: Security, deployment, design, launching"],realWorldExample:"Students who complete this course have gone on to build internal tools at work, launch side projects, and even start companies — all without learning traditional programming.",eli10:"Think of this like levels in a game. You just finished the tutorial! Now the real adventure begins. Each level teaches you new superpowers!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What's the next module about?",["Advanced AI","The language of tech — learning vocabulary","Building a startup","Learning Python"],1,"Module 2 teaches you the vocabulary every vibe coder needs to communicate effectively."),tf("You need to complete modules in order.",true,"Modules build on each other. Later modules assume knowledge from earlier ones.")]),
    challenge:undefined},
];

for (const l of m1Lessons) {
  await prisma.lesson.create({data:{...l,moduleId:m1.id}});
  console.log(`  ✅ ${l.slug}`);
}

// ==================== MODULE 2: LANGUAGE OF TECH (15 lessons) ====================
console.log('\n📖 Module 2: Language of Tech');
const m2 = modules[1];
const m2Lessons = [
  {title:'What is a Website vs a Web App?',slug:'website-vs-webapp',order:1,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"A website is like a newspaper — you read it but can't change it. A web app is like a spreadsheet — you interact with it, enter data, and it responds. Google.com (search) is a web app. A blog is a website. Facebook is a web app. A restaurant menu page is a website. The difference matters because building a web APP requires a backend (server + database), while a simple website might only need a frontend.",keyPoints:["Website = static content you read (blog, portfolio, menu)","Web app = interactive, responds to your actions (Gmail, Twitter, Notion)","Websites: mainly frontend (HTML, CSS, JS)","Web apps: frontend + backend + database","Most things you'll build with AI are web apps"],realWorldExample:"When you scroll Instagram (web app), every like, comment, and follow is processed by a backend server and stored in a database. A restaurant's simple menu page (website) just displays text and images.",eli10:"A website is like a poster on a wall — you look at it. A web app is like a video game — you click buttons and things happen!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("Which is a web APP?",["A blog post","A restaurant menu","Gmail","A Wikipedia article"],2,"Gmail lets you compose, send, receive, and organize emails — that's interactive = web app."),mcq("What extra parts does a web app need compared to a simple website?",["Just HTML","A backend server and database","Only CSS","A mobile app"],1,"Web apps need servers to process logic and databases to store user data.")]),
    challenge:undefined},

  {title:'Frontend: What Users See',slug:'frontend-explained',order:2,difficulty:'BEGINNER' as const,estimatedMinutes:6,
    concept:JSON.stringify({story:"The frontend is everything you can see and touch in a browser. It's built with three languages working together like a team: HTML is the skeleton (structure), CSS is the clothing (style), and JavaScript is the brain (interactivity). When you use Lovable or v0, the AI writes all three for you. But understanding what they do helps you give better prompts!",keyPoints:["HTML = Structure (headings, paragraphs, buttons, forms)","CSS = Style (colors, fonts, spacing, layout, animations)","JavaScript = Behavior (click handlers, form validation, dynamic content)","React, Vue, Angular = frameworks that organize JS for complex apps","Frontend runs in the USER'S browser, not on a server"],realWorldExample:"When you see a blue 'Buy Now' button: HTML created the button element. CSS made it blue and rounded. JavaScript makes something happen when you click it.",eli10:"Building a frontend is like building a house. HTML is the walls and rooms (structure). CSS is the paint and decorations (making it pretty). JavaScript is the electricity and plumbing (making things work when you flip a switch)."}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What does CSS do?",["Creates the page structure","Adds interactivity","Controls visual style (colors, fonts, layout)","Stores data"],2,"CSS = Cascading Style Sheets. It controls how things LOOK: colors, sizes, spacing, animations."),mcq("What does JavaScript do in the frontend?",["Structures the page","Styles the page","Makes things interactive (clicks, forms, animations)","Stores data in a database"],2,"JavaScript handles interactivity: what happens when you click buttons, submit forms, scroll, etc."),fb("The three frontend languages are HTML, ___, and JavaScript.","CSS","HTML provides structure, CSS provides style, and JavaScript provides interactivity.")]),
    challenge:undefined},

  {title:'Backend: The Engine Room',slug:'backend-explained',order:3,difficulty:'BEGINNER' as const,estimatedMinutes:6,
    concept:JSON.stringify({story:"The backend is like the kitchen in a restaurant. Customers (users) see the dining room (frontend), but all the real work happens in the kitchen — cooking food (processing data), storing recipes (database), checking IDs (authentication). When you log into Instagram, the backend checks your password, loads your feed from the database, and sends it to your phone. Common backend languages: Node.js (JavaScript), Python, Java, Go.",keyPoints:["Backend = server-side code users never see","Handles: authentication, data processing, business logic","Common languages: Node.js, Python, Java, Ruby, Go","Communicates with frontend via APIs","Connects to databases to store/retrieve data","Runs on servers (someone else's computer)"],realWorldExample:"When you post a photo on Instagram: your phone (frontend) sends the image to Instagram's servers (backend), which saves it to a database, processes it, and then shows it to your followers.",eli10:"The backend is like the kitchen in a restaurant. You (the user) sit in the dining room and order food. The kitchen cooks it and brings it to you. You never see the kitchen, but without it, there's no food!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("Where does the backend run?",["In the user's browser","On a server","On the user's phone","In the CSS file"],1,"Backend code runs on servers — remote computers that process requests and return responses."),mcq("What does the backend handle?",["Page colors and fonts","Authentication, data storage, and business logic","Only images","Only HTML"],1,"Backend handles the serious stuff: verifying users, saving data, processing payments, etc.")]),
    challenge:undefined},

  {title:'How Frontend Talks to Backend (APIs)',slug:'apis-explained',order:4,difficulty:'BEGINNER' as const,estimatedMinutes:7,
    concept:JSON.stringify({story:"APIs (Application Programming Interfaces) are how the frontend and backend communicate. Think of it like ordering pizza. You (frontend) call the pizza place (backend) and say 'I want a large pepperoni.' They make it and deliver it. The PHONE CALL is the API. Technically: the frontend sends an HTTP REQUEST to the backend's API endpoint, and the backend sends back a RESPONSE with data (usually in JSON format). The 4 main request types: GET (read), POST (create), PUT (update), DELETE (remove).",keyPoints:["API = the 'phone line' between frontend and backend","Frontend sends REQUESTS, backend sends RESPONSES","GET = read data, POST = create data, PUT = update, DELETE = remove","Data is sent in JSON format (like a structured text file)","APIs also connect apps to external services (Google Maps, Stripe, OpenAI)","Every time you load a page, dozens of API calls happen behind the scenes"],realWorldExample:"When you open Uber: GET request fetches nearby drivers. POST request creates a ride when you tap 'Request'. PUT updates your destination. DELETE cancels the ride.",eli10:"An API is like a waiter in a restaurant. You (frontend) tell the waiter what you want. The waiter goes to the kitchen (backend), gets your food, and brings it back. The waiter is the API!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What is an API?",["A programming language","A way for frontend and backend to communicate","A type of database","A design tool"],1,"API = Application Programming Interface. It's the communication bridge between different parts of an app."),mcq("Which HTTP method CREATES new data?",["GET","POST","DELETE","CSS"],1,"POST creates new data. GET reads, PUT updates, DELETE removes."),fb("APIs send data in ___ format, which looks like structured text with key-value pairs.","JSON","JSON (JavaScript Object Notation) is the universal format for API data exchange.")]),
    challenge:undefined},

  {title:'Databases: Where Your Data Lives',slug:'databases-explained',order:5,difficulty:'BEGINNER' as const,estimatedMinutes:6,
    concept:JSON.stringify({story:"A database is like a super-powered spreadsheet. It stores all your app's data: user accounts, posts, messages, orders, everything. There are two main types: SQL databases (like Excel — organized rows and columns with strict rules) and NoSQL databases (like a filing cabinet — flexible, documents of different shapes). SQL examples: PostgreSQL, MySQL. NoSQL examples: MongoDB, Firebase.",keyPoints:["Database = organized storage for your app's data","SQL: rows + columns, strict structure (like Excel spreadsheets)","NoSQL: flexible documents (like filing folders)","SQL is best when data is structured and related","NoSQL is best when data varies in shape","Most vibe coding tools use PostgreSQL (SQL) or Firebase/Supabase"],realWorldExample:"Your bank uses SQL databases (strict structure for financial data). Twitter might use NoSQL (flexible for different types of content). Most apps use SQL — and that's what Lovable, Bolt, and Supabase give you.",eli10:"A database is like a giant organized bookshelf. SQL is a library where every book has to go in a specific spot. NoSQL is more like a bedroom where you can put things wherever, but it's still organized enough to find stuff!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What's the main difference between SQL and NoSQL?",["Speed","SQL has strict structure (tables), NoSQL is flexible (documents)","Cost","SQL is newer"],1,"SQL = strict tables with rows/columns. NoSQL = flexible documents that can have different shapes."),mcq("Which database type do most vibe coding tools use?",["NoSQL only","SQL (PostgreSQL via Supabase)","Flat files","No database"],1,"Most AI coding platforms (Lovable, Bolt) use Supabase, which is built on PostgreSQL (SQL).")]),
    challenge:undefined},

  {title:'SQL vs NoSQL: When to Use Which',slug:'sql-vs-nosql',order:6,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Choosing SQL vs NoSQL is like choosing between a spreadsheet and a notebook. SQL (spreadsheet): Perfect when your data has a clear structure — users, orders, products. Every row looks the same. NoSQL (notebook): Great when data varies — some posts have images, some have videos, some have polls. Each 'document' can be different. Rule of thumb: if you can imagine your data in a spreadsheet → SQL. If your data is messy and varied → NoSQL. When in doubt, SQL is almost always the safe choice.",keyPoints:["SQL: Structured data, relationships between tables","NoSQL: Flexible data, each record can be different","SQL: Users, Orders, Products, Payments → perfect fit","NoSQL: Social feeds, logs, IoT data → flexible fit","When in doubt, choose SQL (safer for most apps)","Supabase (SQL) is the most common in vibe coding tools"],realWorldExample:"Airbnb uses SQL for bookings (structured: dates, prices, users). They might use NoSQL for search (flexible: location data, filters, rankings).",eli10:"SQL is like a spreadsheet — every row has the same columns (name, age, email). NoSQL is like a scrapbook — each page can have different stuff (photos, stickers, drawings, notes)."}),
    demo:undefined,
    quiz:JSON.stringify([mcq("When should you use SQL?",["When data is unstructured","When data has clear structure with relationships","When you don't need a database","For images only"],1,"SQL excels with structured, relational data: users, orders, products, etc."),tf("When in doubt, SQL is the safer default choice.",true,"SQL works for the vast majority of applications and is better supported by AI coding tools.")]),
    challenge:undefined},

  {title:'What is a Tech Stack?',slug:'what-is-tech-stack',order:7,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"A tech stack is the combination of technologies used to build an app — like a recipe listing all ingredients. A typical stack: React (frontend) + Node.js (backend) + PostgreSQL (database) + Vercel (hosting). When someone says 'What stack are you using?', they're asking about your ingredients list. Different stacks suit different needs. Vibe coding tools choose the stack for you, but knowing what they chose helps you debug and extend your app.",keyPoints:["Tech stack = combination of all technologies in your app","Frontend: React, Vue, Angular, Svelte","Backend: Node.js, Python, Ruby, Go","Database: PostgreSQL, MongoDB, Firebase","Hosting: Vercel, Netlify, AWS, Replit","AI tools pick the stack for you, but knowing it helps"],realWorldExample:"Netflix: React (frontend) + Java/Node.js (backend) + Cassandra (database) + AWS (hosting). Lovable typically generates: React + Supabase (backend + database) + Lovable hosting.",eli10:"A tech stack is like a recipe. To make a cake you need flour, eggs, sugar, and an oven. To make an app you need a frontend, backend, database, and hosting. Different cakes use different recipes!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What is a tech stack?",["A pile of code","The combination of technologies used to build an app","A type of database","A hosting platform"],1,"Tech stack = your app's complete ingredient list: frontend + backend + database + hosting."),fb("A typical modern stack is React (frontend) + Node.js (backend) + ___ (database) + Vercel (hosting).","PostgreSQL","PostgreSQL is the most popular database for modern web apps, used by Supabase and many AI tools.")]),
    challenge:undefined},

  {title:'Popular Stacks: MERN, Next.js, JAMstack',slug:'popular-stacks',order:8,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Some tech stacks are so popular they have names! MERN = MongoDB + Express + React + Node.js (the classic full-stack JavaScript stack). Next.js stack = Next.js + PostgreSQL + Vercel (the modern favorite — what v0 and Lovable often generate). JAMstack = JavaScript + APIs + Markup (for fast static sites). You don't need to memorize these, but recognizing them helps you understand AI-generated code and tool documentation.",keyPoints:["MERN: MongoDB, Express, React, Node.js — all JavaScript","Next.js: React framework + PostgreSQL + Vercel — modern favorite","JAMstack: JavaScript, APIs, Markup — fast static sites","Most AI tools generate Next.js or React + Supabase","Knowing the stack name helps you search for solutions"],realWorldExample:"When Lovable builds your app, it typically uses React + TypeScript + Tailwind CSS + Supabase. That's essentially a Next.js-style stack. Bolt uses a similar combination.",eli10:"These are like famous recipes that everyone knows. Just like 'chocolate chip cookies' tells a baker everything they need to know, 'MERN stack' tells a developer what ingredients the app uses."}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What does MERN stand for?",["Modern Efficient Reactive Network","MongoDB, Express, React, Node.js","Multiple Endpoint REST Navigation","Meta Engineering Runtime Node"],1,"MERN = MongoDB (database) + Express (backend framework) + React (frontend) + Node.js (runtime)."),mcq("Which stack do most AI coding tools generate?",["LAMP (PHP)","MERN","React/Next.js + Supabase (PostgreSQL)","Ruby on Rails"],2,"Modern AI tools like Lovable and Bolt typically generate React or Next.js with Supabase.")]),
    challenge:undefined},

  {title:'URLs, Domains & DNS',slug:'urls-domains-dns',order:9,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"When you type google.com, how does your browser know where to go? DNS (Domain Name System) is the internet's phone book. It translates human-friendly names (google.com) into computer-friendly IP addresses (142.251.32.46). A URL is the full address: https://www.google.com/search?q=vibe+coding. A domain is just the name part: google.com. You buy domains from registrars like Namecheap or GoDaddy.",keyPoints:["URL = full address (https://example.com/page)","Domain = the name (example.com)","DNS = translates domains to IP addresses","IP address = the computer's actual address (like a phone number)","Buy domains from registrars ($10-15/year)","Vercel/Netlify give you free subdomains (yourapp.vercel.app)"],realWorldExample:"When you deploy on Vercel, you get a free URL like my-app.vercel.app. To use your own domain (myapp.com), you buy it and point its DNS to Vercel's servers.",eli10:"A domain name is like a nickname. Your friend's real address might be '123 Oak Street' (IP address), but you just call them 'Alex' (domain name). DNS is the directory that knows Alex lives at 123 Oak Street."}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What does DNS do?",["Designs websites","Translates domain names to IP addresses","Stores databases","Creates APIs"],1,"DNS = Domain Name System. It's the internet's phone book, turning names into addresses."),fb("A full URL like https://example.com/about has three parts: protocol (https), ___ (example.com), and path (/about).","domain","The domain is the main identifier — the 'name' of the website.")]),
    challenge:undefined},

  {title:'Hosting: Where Your App Lives',slug:'hosting-explained',order:10,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Your app needs to live somewhere so people can access it. That 'somewhere' is a server — a computer that's always on, always connected to the internet. You don't need to buy a server! Cloud platforms rent them to you. For vibe coders, the best options are: Vercel (best for React/Next.js, free tier), Netlify (great for static sites, free tier), Replit (built-in, zero config), and Lovable (hosts for you automatically).",keyPoints:["Hosting = putting your app on a server for the world to access","You rent servers from cloud platforms","Vercel: Best for React/Next.js apps (free tier: 100GB bandwidth)","Netlify: Great for static sites (free tier generous)","Replit: Built-in hosting, zero configuration","Lovable: Hosts your app automatically","Free tiers are plenty for learning and small projects"],realWorldExample:"When you clicked 'Deploy' in Lovable, it uploaded your app to their servers. That's hosting! The URL you got points to that server.",eli10:"Hosting is like renting a locker at school for your project. You put your project in the locker (server), and anyone with the combination (URL) can see it anytime."}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What is hosting?",["Designing a website","Putting your app on a server so people can access it","Writing code","Buying a domain"],1,"Hosting = making your app accessible on the internet by running it on a server."),mcq("Which hosting platform is best for beginners?",["AWS (complex, enterprise-level)","Vercel or Lovable (free, simple, one-click deploy)","Setting up your own server","None — apps don't need hosting"],1,"Vercel and Lovable offer free tiers with one-click deployment. Perfect for beginners.")]),
    challenge:undefined},

  {title:'What is the Cloud?',slug:'what-is-cloud',order:11,difficulty:'BEGINNER' as const,estimatedMinutes:4,
    concept:JSON.stringify({story:"'The cloud' sounds mystical, but it's simple: it's just someone else's computer. When you save a photo to iCloud, it's stored on Apple's servers. When you deploy to Vercel, your app runs on Vercel's servers. The big cloud providers are AWS (Amazon), Azure (Microsoft), and GCP (Google). They have millions of servers worldwide. You rent tiny slices of these servers, pay only for what you use, and scale up if needed.",keyPoints:["The cloud = someone else's computer (servers you rent)","Big three: AWS (Amazon), Azure (Microsoft), GCP (Google)","You pay only for what you use","Can scale from 1 user to 1 million without buying hardware","Vercel, Netlify, Replit run ON TOP of these cloud providers","'Serverless' = cloud manages the server for you"],realWorldExample:"Netflix runs on AWS. When millions watch a show, AWS automatically provides more servers. When viewership drops, it scales back. You only pay for what you use.",eli10:"The cloud is like a really big garage where you can store your stuff. Instead of buying your own garage, you rent a tiny space. If you need more room, you just rent more. That's the cloud!"}),
    demo:undefined,
    quiz:JSON.stringify([tf("The cloud is just other people's computers that you rent.",true,"Despite the fancy name, cloud computing is simply renting server space from companies like Amazon, Microsoft, or Google."),mcq("What does 'serverless' mean?",["No servers are used","You don't manage the server — the cloud provider does","It runs on your local computer","It's offline"],1,"'Serverless' doesn't mean no servers — it means you don't have to manage them. The cloud handles everything.")]),
    challenge:undefined},

  {title:'Mobile Apps vs Web Apps vs PWAs',slug:'mobile-web-pwa',order:12,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Three ways to build 'apps' for phones: Native mobile apps (Swift for iOS, Kotlin for Android) — downloaded from App Store/Play Store. Web apps — websites that work on phones (like mobile Twitter). PWAs (Progressive Web Apps) — web apps that feel native (can be 'installed', work offline, send notifications). For vibe coders, web apps and PWAs are the way to go — you build once and it works everywhere. No App Store approval needed!",keyPoints:["Native: Built for one platform (iOS or Android), best performance","Web app: Website that works on phones, one codebase for all","PWA: Web app with native-like features (install, offline, notifications)","Vibe coding mostly produces web apps (works everywhere!)","No App Store review process for web apps","React apps are automatically mobile-responsive if designed well"],realWorldExample:"Twitter.com on your phone is a PWA. It can be 'installed' to your home screen, sends notifications, and works like a native app — but it's a website!",eli10:"Native apps are like specific toys made for one kid. Web apps are like toys any kid can play with. PWAs are web toys that are SO good they feel like they were made just for you!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What's the best approach for vibe coders?",["Build native iOS and Android apps separately","Build a web app (works everywhere, one codebase)","Only build desktop apps","Don't build for mobile"],1,"Web apps work on all devices with one codebase. No app store approval needed. Perfect for vibe coding."),mcq("What is a PWA?",["A programming language","A web app with native-like features (install, offline, notifications)","A database type","An AI tool"],1,"PWA = Progressive Web App. It's a website that can be installed, works offline, and sends push notifications.")]),
    challenge:undefined},

  {title:'Authentication: How Apps Know Who You Are',slug:'authentication-explained',order:13,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"When you log into Instagram, how does it know it's you? Authentication! The most common flow: you enter email + password. The backend checks if they match. If yes, it gives you a 'token' (like a wristband at a concert). Your browser stores this token and shows it with every request. The server sees the wristband and says 'cool, you're allowed in.' Modern apps also support OAuth (login with Google/GitHub) and Magic Links (link sent to your email).",keyPoints:["Authentication = verifying who you are","Password + email → backend verifies → gives you a token","Token = your 'access pass' stored in the browser","JWT (JSON Web Token) = most common token format","OAuth = 'Login with Google/GitHub' (easiest for users)","Never store passwords in plain text — always hashed!"],realWorldExample:"When Lovable lets you 'Sign in with Google', that's OAuth. Google confirms your identity and tells Lovable 'yes, this person is who they say they are.'",eli10:"Authentication is like showing your ID to get into a movie. You prove who you are (password), get a ticket (token), and show the ticket to get into different rooms (pages)."}),
    demo:undefined,
    quiz:JSON.stringify([mcq("What is a token in authentication?",["A physical coin","An access pass that proves you're logged in","A password","An API key"],1,"A token is a digital 'wristband' that proves you've already verified your identity."),tf("Passwords should be stored exactly as the user types them.",false,"NEVER store plain text passwords! They must be 'hashed' (scrambled) before storage. If the database leaks, hashed passwords are unreadable.")]),
    challenge:undefined},

  {title:'Real-time vs Request-Response',slug:'realtime-vs-request',order:14,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"Most web communication is request-response: you ask for something (request), the server gives it back (response). Like sending a letter and waiting for a reply. But some features need real-time: chat messages, live notifications, stock prices, multiplayer games. For real-time, we use WebSockets — an always-open connection, like a phone call instead of letters. Supabase and Firebase both support real-time updates.",keyPoints:["Request-Response: Client asks → Server answers (like letters)","Real-time: Constant open connection (like a phone call)","WebSockets enable real-time communication","Use request-response for: loading pages, submitting forms, searching","Use real-time for: chat, notifications, live updates, collaboration","Supabase Realtime and Firebase both support this"],realWorldExample:"Google Docs is real-time — you see other people's edits as they type. A blog is request-response — you load it once, and it doesn't change until you refresh.",eli10:"Request-response is like texting — you send a message and wait for a reply. Real-time is like a phone call — you hear each other instantly, all the time!"}),
    demo:undefined,
    quiz:JSON.stringify([mcq("Which feature needs real-time communication?",["Loading a profile page","Submitting a form","Live chat messages","Searching for products"],2,"Chat requires instant delivery of messages — that's real-time via WebSockets."),mcq("What technology enables real-time web communication?",["HTML","CSS","WebSockets","DNS"],2,"WebSockets maintain a persistent connection between client and server for instant two-way communication.")]),
    challenge:undefined},

  {title:'Quiz: Can You Speak Tech Now?',slug:'speak-tech-quiz',order:15,difficulty:'BEGINNER' as const,estimatedMinutes:5,
    concept:JSON.stringify({story:"You've completed Module 2! Let's test your new vocabulary. You now know the difference between frontend and backend, how APIs connect them, what databases store, what a tech stack is, and how hosting and deployment work. This knowledge is your SUPERPOWER as a vibe coder — you can now give AI tools much more precise instructions because you understand what they're building.",keyPoints:["Frontend = what users see (HTML, CSS, JS)","Backend = server logic (Node.js, Python)","API = communication between frontend ↔ backend","Database = where data is stored (SQL vs NoSQL)","Hosting = putting your app on the internet","Tech stack = all technologies combined"],realWorldExample:"Now when an AI tool asks 'Do you want Supabase for your backend?' you know that means 'Do you want a PostgreSQL database with built-in authentication and APIs?'",eli10:"You just learned a whole new language! Like learning Spanish means you can talk to more people, learning tech-speak means you can talk to AI tools better!"}),
    demo:undefined,
    quiz:JSON.stringify([
      mcq("What's the difference between frontend and backend?",["Frontend is slower","Frontend = what users see, Backend = server logic users don't see","Frontend costs more","There is no difference"],1,"Frontend is the user interface. Backend is the invisible server processing logic."),
      fb("The four HTTP methods are GET (read), POST (create), ___ (update), and DELETE (remove).","PUT","GET reads, POST creates, PUT updates, DELETE removes. These are the four pillars of REST APIs."),
      mcq("SQL databases organize data in:",["Random piles","Rows and columns (like spreadsheets)","Alphabetical lists","Binary trees"],1,"SQL = tables with rows and columns. Each row is a record, each column is a field."),
      mcq("What translates domain names to IP addresses?",["HTTP","CSS","DNS","APIs"],2,"DNS (Domain Name System) is the internet's phone book, turning names into IP addresses."),
      tf("PWAs can work offline and be installed on phones like native apps.",true,"Progressive Web Apps support offline mode, installation, and push notifications — bridging the gap between web and native."),
      mcq("Which is NOT a hosting platform?",["Vercel","Netlify","PostgreSQL","Replit"],2,"PostgreSQL is a DATABASE, not a hosting platform. Vercel, Netlify, and Replit all provide hosting.")
    ]),
    challenge:JSON.stringify({type:"project_task",description:"Write a one-paragraph description of an app idea, using at least 5 tech terms you learned (frontend, backend, API, database, hosting, etc.). Example: 'I want to build a web app with a React frontend...'",criteria:["Uses at least 5 tech terms correctly","Describes a realistic app idea","Mentions frontend and backend","Mentions database or API"],xpBonus:50})},
];

for (const l of m2Lessons) {
  await prisma.lesson.create({data:{...l,moduleId:m2.id}});
  console.log(`  ✅ ${l.slug}`);
}

// ==================== BADGES ====================
console.log('\n🏅 Badges');
await prisma.badge.createMany({data:[
  {name:'First Deploy',description:'Deploy your first app to the internet',icon:'🚀',criteria:{type:'project_completed',count:1},category:'milestone'},
  {name:'Lesson Learner',description:'Complete your first lesson',icon:'📚',criteria:{type:'lessons_completed',count:1},category:'milestone'},
  {name:'Getting Started',description:'Complete 5 lessons',icon:'⭐',criteria:{type:'lessons_completed',count:5},category:'milestone'},
  {name:'Double Digits',description:'Complete 10 lessons',icon:'🔟',criteria:{type:'lessons_completed',count:10},category:'milestone'},
  {name:'Module Master',description:'Complete an entire module',icon:'🏆',criteria:{type:'modules_completed',count:1},category:'skill'},
  {name:'Prompt Apprentice',description:'Complete the Prompt Engineering module',icon:'✨',criteria:{type:'module_slug',slug:'prompt-engineering'},category:'skill'},
  {name:'Security Guard',description:'Complete the Security module with 100%',icon:'🛡️',criteria:{type:'module_slug',slug:'security'},category:'skill'},
  {name:'Multi-Tool Master',description:'Complete the AI Toolbox module',icon:'🧰',criteria:{type:'module_slug',slug:'ai-toolbox'},category:'skill'},
  {name:'Git Guru',description:'Complete the Git module',icon:'🔀',criteria:{type:'module_slug',slug:'git'},category:'skill'},
  {name:'Ship Captain',description:'Complete the Ship It module',icon:'🚢',criteria:{type:'module_slug',slug:'ship-it'},category:'skill'},
  {name:'Week Warrior',description:'7-day learning streak',icon:'🔥',criteria:{type:'streak_days',count:7},category:'milestone'},
  {name:'Streak Lord',description:'30-day learning streak',icon:'💪',criteria:{type:'streak_days',count:30},category:'milestone'},
  {name:'Halfway There',description:'Complete 50% of all lessons',icon:'⚡',criteria:{type:'lessons_completed',count:64},category:'milestone'},
  {name:'Vibe Coder',description:'Reach level 20',icon:'🧠',criteria:{type:'level_reached',count:20},category:'milestone'},
  {name:'Technical Founder',description:'Complete ALL lessons',icon:'👑',criteria:{type:'lessons_completed',count:128},category:'milestone'},
]});

// ==================== GLOSSARY (50 key terms) ====================
console.log('\n📖 Glossary');
const glossaryTerms = [
  {term:'API',definition:'Application Programming Interface — a set of rules that lets different software applications communicate with each other.',eli10:'A waiter in a restaurant. You tell the waiter what you want, the waiter tells the kitchen, and brings your food back.',category:'tech',relatedTerms:JSON.stringify(['REST','endpoint','JSON','HTTP'])},
  {term:'Frontend',definition:'The part of a website or app that users see and interact with — built with HTML, CSS, and JavaScript.',eli10:'The outside of a building — the doors, windows, and paint that everyone sees.',category:'tech',relatedTerms:JSON.stringify(['HTML','CSS','JavaScript','React'])},
  {term:'Backend',definition:'The server-side part of an application that handles logic, database operations, and authentication — invisible to users.',eli10:'The kitchen in a restaurant. You never see it, but all the important cooking happens there.',category:'tech',relatedTerms:JSON.stringify(['server','Node.js','API','database'])},
  {term:'Database',definition:'An organized collection of data stored electronically. Can be SQL (structured tables) or NoSQL (flexible documents).',eli10:'A super-organized bookshelf where you can instantly find any book.',category:'tech',relatedTerms:JSON.stringify(['SQL','NoSQL','PostgreSQL','MongoDB'])},
  {term:'HTML',definition:'HyperText Markup Language — the skeleton of every web page, defining its structure and content.',eli10:'The building blocks of a web page — like the walls and rooms of a house.',category:'tech',relatedTerms:JSON.stringify(['CSS','JavaScript','frontend','tag'])},
  {term:'CSS',definition:'Cascading Style Sheets — controls the visual appearance of web pages: colors, fonts, layout, animations.',eli10:'The paint, decorations, and furniture that make a house look nice.',category:'tech',relatedTerms:JSON.stringify(['HTML','Tailwind','responsive','styling'])},
  {term:'JavaScript',definition:'The programming language of the web. Adds interactivity to websites and can run both in browsers and on servers (Node.js).',eli10:'The electricity in a house — it makes things work when you flip switches and press buttons.',category:'tech',relatedTerms:JSON.stringify(['TypeScript','Node.js','React','frontend'])},
  {term:'React',definition:'A JavaScript library by Meta for building user interfaces. The most popular frontend framework.',eli10:'A set of pre-built LEGO pieces that make it faster to build complicated things.',category:'tech',relatedTerms:JSON.stringify(['Next.js','component','JSX','frontend'])},
  {term:'Node.js',definition:'A JavaScript runtime that lets you run JavaScript on servers (backend), not just in browsers.',eli10:'JavaScript escaped from the browser and now works in the kitchen (server) too!',category:'tech',relatedTerms:JSON.stringify(['JavaScript','Express','backend','npm'])},
  {term:'Git',definition:'A version control system that tracks changes to your code over time. Like infinite undo + save points.',eli10:'A time machine for your code. You can go back to any point in time and see what things looked like.',category:'tech',relatedTerms:JSON.stringify(['GitHub','commit','branch','repository'])},
  {term:'GitHub',definition:'A website that hosts Git repositories online. Where most open-source code lives.',eli10:'A social media site for code. People share their projects and work together.',category:'tech',relatedTerms:JSON.stringify(['Git','repository','pull request','open source'])},
  {term:'JSON',definition:'JavaScript Object Notation — a text format for storing and exchanging data. Used by virtually all APIs.',eli10:'A recipe card with clear labels. Each ingredient has a name and a value.',category:'tech',relatedTerms:JSON.stringify(['API','data','object','key-value'])},
  {term:'REST',definition:'Representational State Transfer — a standard way to design APIs using HTTP methods (GET, POST, PUT, DELETE).',eli10:'A set of rules for how to ask the waiter (API) for things. GET = look at the menu, POST = order food.',category:'tech',relatedTerms:JSON.stringify(['API','HTTP','endpoint','CRUD'])},
  {term:'Deployment',definition:'The process of taking your code and making it live on the internet for users to access.',eli10:'Putting your art project on display in the school hallway so everyone can see it.',category:'deployment',relatedTerms:JSON.stringify(['hosting','Vercel','Netlify','CI/CD'])},
  {term:'DNS',definition:'Domain Name System — translates human-readable domain names (google.com) to IP addresses (142.251.32.46).',eli10:"The internet's phone book. You look up a name and get an address.",category:'tech',relatedTerms:JSON.stringify(['domain','IP address','URL','hosting'])},
  {term:'Environment Variables',definition:'Configuration values (like API keys and passwords) stored outside your code for security.',eli10:'Secret notes you keep in a locked drawer, not taped to the fridge where everyone can see them.',category:'security',relatedTerms:JSON.stringify(['.env','secrets','API key','configuration'])},
  {term:'Prompt Engineering',definition:'The skill of writing effective instructions for AI models to get the best possible output.',eli10:'Learning exactly how to ask your super-smart robot helper to build things the way you want.',category:'tech',relatedTerms:JSON.stringify(['AI','vibe coding','context','iteration'])},
  {term:'Token',definition:'In auth: a digital pass proving identity. In AI: a unit of text (~4 characters) that models process.',eli10:'A wristband at a theme park. Once you get it, you can ride all the rides without buying tickets each time.',category:'security',relatedTerms:JSON.stringify(['JWT','authentication','session','API key'])},
  {term:'Responsive Design',definition:'Designing websites that look good on all screen sizes — phones, tablets, and desktops.',eli10:'A stretchy shirt that fits kids AND adults. The website stretches to fit any screen!',category:'design',relatedTerms:JSON.stringify(['mobile-first','CSS','media query','layout'])},
  {term:'Component',definition:'A reusable piece of UI in frameworks like React. A button, a card, a navigation bar are all components.',eli10:'A LEGO brick. You can use the same brick in many different creations.',category:'tech',relatedTerms:JSON.stringify(['React','reusable','UI','props'])},
  {term:'NPM',definition:'Node Package Manager — a tool to install and manage code libraries (packages) for JavaScript projects.',eli10:'An app store for code pieces. Instead of building everything yourself, you download pre-made parts.',category:'tech',relatedTerms:JSON.stringify(['Node.js','package','dependency','library'])},
  {term:'TypeScript',definition:'A superset of JavaScript that adds type checking — catches bugs before code runs.',eli10:'JavaScript with spell-check. It catches mistakes as you write, not after.',category:'tech',relatedTerms:JSON.stringify(['JavaScript','types','compile','strict'])},
  {term:'Supabase',definition:'An open-source Firebase alternative providing database, auth, storage, and real-time APIs. Built on PostgreSQL.',eli10:'A ready-made backend in a box. Database, user login, and file storage all included.',category:'tech',relatedTerms:JSON.stringify(['PostgreSQL','Firebase','backend','auth'])},
  {term:'Vercel',definition:'A cloud platform for deploying web applications, especially Next.js and React. Free tier available.',eli10:'A free display case on the internet where you put your website for everyone to see.',category:'deployment',relatedTerms:JSON.stringify(['deployment','Next.js','hosting','CDN'])},
  {term:'Tailwind CSS',definition:'A utility-first CSS framework that lets you style elements with pre-built class names instead of writing custom CSS.',eli10:'Instead of mixing paint colors yourself, you have thousands of pre-mixed colors to choose from.',category:'tech',relatedTerms:JSON.stringify(['CSS','styling','utility','responsive'])},
];
await prisma.glossaryTerm.createMany({data:glossaryTerms});

const totalLessons = await prisma.lesson.count();
const totalGlossary = await prisma.glossaryTerm.count();
console.log(`\n🎉 Seeding complete!`);
console.log(`  ${modules.length} modules`);
console.log(`  ${totalLessons} lessons`);
console.log(`  ${totalGlossary} glossary terms`);
console.log(`  15 badges`);
}

main().catch(console.error).finally(()=>prisma.$disconnect());
