import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

function t(term:string,definition:string,eli10:string,category:string,related:string[]){
  return {term,definition,eli10,category,relatedTerms:JSON.stringify(related)};
}

async function main(){
console.log('📖 Expanding Glossary to 100+ terms...\n');

const terms = [
  // Already have 25, add 80+ more
  t("Framework","A pre-built structure of code that provides common functionality so you don't start from scratch.","A framework is like a pre-built LEGO base plate. You don't build the flat part — you start building on top of it!","tech",["React","Next.js","Express","library"]),
  t("Library","A collection of pre-written code you can use in your project. Unlike frameworks, you call libraries — they don't call you.","A library is like a box of special tools. You pick the ones you need when you need them.","tech",["npm","package","dependency","framework"]),
  t("Dependency","An external package your project needs to work. Listed in package.json for JavaScript projects.","Dependencies are like ingredients in a recipe. Your cake (app) needs flour (React), eggs (Express), etc. to work.","tech",["npm","package.json","library","node_modules"]),
  t("Package","A bundle of code published to a registry (npm, PyPI) that others can install and use.","A package is like a pre-made kit from the store. Instead of making everything yourself, you buy kits and put them together.","tech",["npm","library","dependency","registry"]),
  t("Runtime","The environment where your code actually executes. Node.js is a JavaScript runtime for servers.","A runtime is like the stage where actors perform. The code is the script, the runtime is the theater where it comes alive.","tech",["Node.js","browser","engine","execution"]),
  t("Compiler","A program that translates code from one language to another (TypeScript → JavaScript, for example).","A compiler is like a translator at the UN. They take a speech in French (TypeScript) and translate it to English (JavaScript).","tech",["TypeScript","build","transpile","Babel"]),
  t("IDE","Integrated Development Environment — a code editor with built-in tools like debugging, terminal, and autocomplete.","An IDE is like a super desk with everything built in: pen holder, lamp, calculator, and magnifying glass. All your tools in one place!","tech",["VS Code","Cursor","editor","IntelliJ"]),
  t("Terminal","A text-based interface for interacting with your computer using commands instead of clicking.","The terminal is like talking to your computer using letters instead of pictures. You type commands, it does things.","tech",["CLI","bash","shell","command line"]),
  t("CLI","Command Line Interface — a program you interact with by typing text commands in the terminal.","A CLI is like texting your computer. Instead of pressing buttons, you type what you want it to do.","tech",["terminal","bash","npm","git"]),
  t("Localhost","Your own computer acting as a server during development. Accessible at http://localhost:3000.","Localhost is like cooking in your own kitchen before opening a restaurant. Only you can taste the food (see the app).","deployment",["server","development","port","127.0.0.1"]),
  t("Port","A number that identifies a specific service on a computer. Like apartment numbers in a building.","If your computer is a building, ports are apartment numbers. Port 3000 is apartment 3000 — that's where your app lives!","tech",["localhost","server","HTTP","3000"]),
  t("Repository","A folder tracked by Git containing your project's files and their entire change history.","A repo is like a magical photo album that remembers every version of every photo ever taken.","tech",["Git","GitHub","clone","remote"]),
  t("Commit","A snapshot of your project saved in Git with a descriptive message explaining what changed.","A commit is like taking a photo and writing on the back what happened: 'Added login page, April 15'.","tech",["Git","snapshot","message","push"]),
  t("Branch","A parallel version of your code for working on features without affecting the main codebase.","A branch is like a parallel universe. You can experiment there, and if it works, merge it back to the main universe!","tech",["Git","merge","main","feature"]),
  t("Merge","Combining changes from one Git branch into another, usually bringing a feature branch into main.","Merging is like combining two puzzle pieces. If they fit (no conflicts), they snap together perfectly.","tech",["Git","branch","conflict","pull request"]),
  t("Pull Request","A GitHub feature requesting that changes from your branch be reviewed and merged into main.","A PR is like raising your hand: 'I finished this work — can someone check it before we add it to the project?'","tech",["GitHub","code review","merge","branch"]),
  t("Endpoint","A specific URL path that an API responds to, like /api/users or /api/products/:id.","An endpoint is like a specific counter at a government office. /users goes to the 'Users' counter, /products to 'Products'.","tech",["API","REST","route","URL"]),
  t("CRUD","Create, Read, Update, Delete — the four basic operations for managing data.","CRUD is like the four things you can do with a notebook: write something new, read it, change it, or erase it.","tech",["API","database","REST","HTTP methods"]),
  t("ORM","Object-Relational Mapping — a tool that lets you interact with databases using code instead of SQL.","An ORM is like a translator between your code and the database. You speak JavaScript, it speaks SQL, everyone's happy!","tech",["Prisma","database","SQL","model"]),
  t("Prisma","A modern ORM for Node.js/TypeScript that makes database operations type-safe and easy.","Prisma is like an automatic filing system. You describe what you want to store, and it handles all the organization.","tech",["ORM","database","PostgreSQL","schema"]),
  t("Migration","A file that describes changes to your database structure (add table, change column, etc.).","A migration is like a renovation blueprint. 'Step 1: add a new room. Step 2: widen the doorway.' It tracks all changes.","tech",["database","Prisma","schema","SQL"]),
  t("Schema","A blueprint defining the structure of your database: tables, columns, types, and relationships.","A schema is like the blueprints for a house. It shows every room (table), every wall (column), and every door (relationship).","tech",["database","Prisma","migration","model"]),
  t("Middleware","Code that runs between receiving a request and sending a response — like a security checkpoint.","Middleware is like a security guard at a building entrance. Every visitor (request) passes through them before entering.","tech",["Express","authentication","API","request"]),
  t("JWT","JSON Web Token — a compact, self-contained token used for authentication between client and server.","A JWT is like a concert wristband. It proves you paid (authenticated) and the bouncer (server) can verify it quickly.","security",["token","authentication","header","session"]),
  t("Hash","A one-way mathematical transformation that converts data into a fixed-size string. Used for passwords.","Hashing is like a paper shredder for passwords. You can verify the right password goes in, but can't reconstruct it from the shreds.","security",["bcrypt","password","encryption","security"]),
  t("Encryption","Converting data into an unreadable format that can only be decoded with a key.","Encryption is like writing in a secret code. Only people with the decoder ring (key) can read the message.","security",["HTTPS","SSL","key","decrypt"]),
  t("SSL/TLS","Security protocols that encrypt data between browser and server. HTTPS uses SSL/TLS.","SSL is like an armored truck for your data. It travels safely from your browser to the server, protected from thieves.","security",["HTTPS","certificate","encryption","security"]),
  t("CORS","Cross-Origin Resource Sharing — security rules about which websites can access your API.","CORS is like a guest list at a party. Only approved websites (origins) are allowed to access your API.","security",["API","origin","browser","security"]),
  t("Webhook","An API that calls YOUR server when an event happens, instead of you polling for changes.","A webhook is like a doorbell. Instead of checking if someone's at the door every 5 minutes, the bell rings when they arrive!","tech",["API","Stripe","event","callback"]),
  t("WebSocket","A persistent two-way connection between client and server for real-time communication.","A WebSocket is like a phone call — both sides can talk anytime. HTTP is like sending letters — you wait for a reply each time.","tech",["real-time","chat","socket","connection"]),
  t("CDN","Content Delivery Network — servers around the world that cache your content close to users.","A CDN is like having copies of your favorite book in every library in the world. Wherever you go, there's a copy nearby!","deployment",["Vercel","Netlify","caching","performance"]),
  t("Caching","Storing a copy of data locally to avoid re-fetching it. Makes apps much faster.","Caching is like keeping frequently used phone numbers written on a sticky note instead of looking them up in the phone book every time.","tech",["CDN","performance","Redis","storage"]),
  t("Serverless","Cloud computing where the provider manages servers. You deploy functions, not servers.","Serverless is like Uber. You don't own a car (server) — you just request a ride (function) when you need one.","deployment",["Lambda","Vercel","cloud","function"]),
  t("Docker","A tool that packages your app with all its dependencies into a 'container' that runs anywhere.","Docker is like a lunchbox. Everything your app needs is packed inside. Open it on any computer and it works!","deployment",["container","DevOps","image","microservice"]),
  t("CI/CD","Continuous Integration/Continuous Deployment — automatic testing and deployment on every code push.","CI/CD is like a factory conveyor belt. You put raw materials in (code), and finished products (deployed app) come out automatically.","deployment",["GitHub Actions","Vercel","pipeline","automation"]),
  t("Linting","Automatically checking code for style issues, bugs, and formatting problems.","A linter is like spell-check for code. It catches typos, bad formatting, and potential mistakes before they cause problems.","tech",["ESLint","Prettier","code quality","formatting"]),
  t("TypeScript","A superset of JavaScript that adds static type checking. Catches bugs before runtime.","TypeScript is like JavaScript with training wheels AND a safety net. It catches mistakes as you type, not after your app crashes.","tech",["JavaScript","types","compile","strict"]),
  t("Tailwind CSS","A utility-first CSS framework where you style elements using pre-defined class names.","Tailwind is like having a box of labeled paint swatches. Instead of mixing colors yourself, you pick from thousands of ready-made options.","tech",["CSS","utility","responsive","styling"]),
  t("shadcn/ui","A popular React component library with pre-built, customizable UI components.","shadcn/ui is like an IKEA for websites. Pre-designed buttons, cards, and menus you can customize and assemble.","tech",["React","component","Tailwind","UI"]),
  t("Next.js","A React framework by Vercel that adds server-side rendering, routing, and more.","Next.js is React with superpowers. React builds the frontend, Next.js adds speed, SEO, and server magic on top.","tech",["React","Vercel","SSR","routing"]),
  t("SaaS","Software as a Service — software delivered via the internet on a subscription basis.","SaaS is like Netflix for software. You pay monthly, use it in your browser, and don't install anything.","tech",["subscription","cloud","product","business"]),
  t("MVP","Minimum Viable Product — the simplest version of your product with just enough features to launch.","An MVP is like a cupcake before a wedding cake. You bake the simplest version first, see if people like it, then go bigger!","tech",["startup","launch","lean","iteration"]),
  t("Responsive","Design that automatically adjusts to different screen sizes (phone, tablet, desktop).","Responsive design is like stretchy pants. They fit you whether you gain or lose weight (screen gets bigger or smaller)!","design",["mobile-first","CSS","breakpoint","media query"]),
  t("Breakpoint","A specific screen width where the layout changes (e.g., 768px for tablet, 1024px for desktop).","Breakpoints are like outfit changes. At home (phone) you wear pajamas, at work (desktop) you wear a suit.","design",["responsive","CSS","media query","mobile"]),
  t("State","Data that changes over time in your app. When state changes, the UI updates automatically.","State is like a scoreboard. When the score (state) changes, the display (UI) automatically shows the new number.","tech",["React","useState","Redux","context"]),
  t("Props","Properties passed from a parent component to a child in React. Like function parameters.","Props are like instructions on a custom order. The parent says 'make this button blue and say Click Me' and passes those instructions down.","tech",["React","component","data","parent"]),
  t("Hook","A React feature that lets you 'hook into' state and lifecycle features in function components.","Hooks are like power-ups in a game. useState gives you memory, useEffect gives you superpowers, each hook adds a new ability.","tech",["React","useState","useEffect","function component"]),
  t("Context","A React feature for sharing data across components without passing props through every level.","Context is like a school PA system. Instead of whispering a message student-to-student (props), the principal broadcasts to everyone at once.","tech",["React","state","provider","global"]),
  t("Rendering","The process of converting your code into visual elements displayed in the browser.","Rendering is like a printer. Your code is the document, rendering turns it into the page you see on screen.","tech",["React","SSR","CSR","DOM"]),
  t("SSR","Server-Side Rendering — generating HTML on the server before sending to the browser. Faster first load.","SSR is like a restaurant bringing your food ready to eat. CSR is like bringing ingredients and cooking at your table.","tech",["Next.js","performance","SEO","CSR"]),
  t("Vibe Coding","Building software by describing what you want to an AI, which generates the code for you.","Vibe coding is telling a super-smart robot exactly what you want built, and it builds it for you. You describe, it creates!","tech",["AI","prompt engineering","Lovable","Cursor"]),
  t("Hallucination","When AI generates plausible but incorrect information — fake APIs, non-existent packages, wrong code.","AI hallucination is like a student making up a confident-sounding answer on a test. It sounds right but is completely wrong!","security",["AI","debugging","verification","slopsquatting"]),
  t("Token","In AI: a unit of text (roughly 4 characters) that models process. Costs are per-token.","In AI, a token is like a word-piece. 'Hello world' is 2 tokens. More tokens = more cost. It's how AI reads and charges.","tech",["AI","OpenAI","cost","API"]),
  t("Open Source","Software whose source code is publicly available for anyone to view, use, and modify.","Open source is like sharing your recipe with the world. Anyone can cook it, improve it, and share their version.","tech",["GitHub","license","MIT","community"]),
  t("SEO","Search Engine Optimization — techniques to help your website rank higher in Google search results.","SEO is like putting a big neon sign on your store facing the highway. It helps people driving by (searching Google) find you.","tech",["Google","meta tags","keywords","ranking"]),
  t("Analytics","Tools and data that show how people use your app: page views, clicks, user behavior, etc.","Analytics is like having a security camera in your store. You can see how many people come in, what they look at, and where they go.","tech",["Google Analytics","Vercel","tracking","data"]),
  t("Agile","A project management approach focused on delivering small increments frequently rather than one big release.","Agile is like eating a pizza one slice at a time instead of trying to eat the whole thing in one bite. Small pieces, delivered regularly.","tech",["scrum","sprint","iteration","kanban"]),
  t("Sprint","A fixed time period (usually 1-2 weeks) in Agile where a team commits to completing specific tasks.","A sprint is like a mini race. You have 2 weeks to finish as many tasks as you can. Then you rest, plan, and sprint again.","tech",["agile","scrum","iteration","velocity"]),
  t("Regex","Regular Expression — a pattern for matching text. Like a super-powered search and replace.","Regex is like a detective's sketch. Instead of searching for an exact person, you search for 'anyone with brown hair and glasses' (a pattern).","tech",["search","pattern","validation","string"]),
  t("Refactoring","Restructuring existing code without changing its behavior. Like reorganizing a closet.","Refactoring is like reorganizing your room. Everything stays the same, but now you can find things faster and it looks neater.","tech",["code quality","clean code","DRY","maintenance"]),
  t("DRY","Don't Repeat Yourself — a principle that says every piece of knowledge should exist in only one place.","DRY is like having ONE recipe card instead of writing the same recipe in 5 different notebooks. Change it once, updated everywhere.","tech",["refactoring","principle","reuse","function"]),
  t("Abstraction","Hiding complex details behind a simpler interface. You use it without knowing how it works inside.","Abstraction is like driving a car. You turn the steering wheel and press pedals. You don't need to know how the engine works!","tech",["encapsulation","interface","API","module"]),
  t("Latency","The time delay between a request and response. Lower latency = faster app.","Latency is like delivery time. Low latency = pizza arrives in 10 minutes. High latency = pizza arrives in 2 hours. Nobody likes waiting!","tech",["performance","CDN","edge","speed"]),
  t("Bandwidth","The amount of data that can be transferred in a given time period. Like the width of a pipe.","Bandwidth is like a highway. More lanes (bandwidth) = more cars (data) can travel at once = less traffic (congestion).","tech",["hosting","CDN","network","speed"]),
  t("Payload","The data sent in an API request or response body. The actual content being transferred.","A payload is like the actual letter inside an envelope. The envelope is the HTTP request, the letter is the payload (data).","tech",["API","request","response","JSON"]),
  t("Pagination","Splitting large lists of data into pages. Instead of loading 10,000 items, load 20 at a time.","Pagination is like a book. Instead of printing all the words on one giant page, you split them into manageable pages.","tech",["API","database","performance","infinite scroll"]),
  t("Indexing","Creating a lookup structure in a database to speed up searches. Like an index in a textbook.","A database index is like a book's table of contents. Instead of reading every page to find a topic, you look it up instantly.","tech",["database","performance","SQL","query"]),
  t("Seed Data","Initial data loaded into a database for testing or setup. Pre-populated content.","Seed data is like the sample products in a new store. They're not real orders, but they make the store look alive and let you test things.","tech",["database","testing","development","migration"]),
  t("Boilerplate","Starter code or template that provides the basic structure for a new project.","Boilerplate is like a pre-built house frame. The foundation and walls are done — you just need to decorate and move in.","tech",["template","starter","scaffold","create-react-app"]),
  t("Scaffold","Auto-generating the basic file structure and code for a project. Like a code skeleton.","Scaffolding is like getting a coloring book. The outlines are drawn for you — you just fill in the colors (code).","tech",["boilerplate","CLI","generator","init"]),
];

// Insert only new terms
let added = 0;
for(const term of terms) {
  const exists = await prisma.glossaryTerm.findUnique({where:{term:term.term}});
  if(!exists) {
    await prisma.glossaryTerm.create({data:term});
    added++;
  }
}

const total = await prisma.glossaryTerm.count();
console.log(`Added ${added} new terms. Total glossary: ${total} terms`);
}

main().catch(console.error).finally(()=>prisma.$disconnect());
